<?php

namespace Webkul\ImageGalleryBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Pim\Component\Catalog\Query\Filter\Operators;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryMediaRepository extends EntityRepository implements \IdentifiableObjectRepositoryInterface
{
    /** @var EntityManager */
    protected $em;

    /** @var string */
    protected $entityName;

    /**
     * @param EntityManager $em
     * @param string        $class
     */
    public function __construct(EntityManager $em, $class)
    {
        parent::__construct($em, $em->getClassMetadata($class));

        $this->em = $em;
        $this->entityName = $class;
    }

    /**
     * {@inheritdoc}
     */
    public function findOneByIdentifier($identifier)
    {
        return $this->findOneBy(['code' => $identifier]);
    }

    /**
     * {@inheritdoc}
     */
    public function getIdentifierProperties()
    {
        return ['media'];
    }

    public function getSingleArrayResultByIdentifiersAndMediaKey($identifier, $filePath)
    {
        $result = $this->getEntityManager()->createQueryBuilder()
                        ->select('m')
                        ->from($this->getEntityName(), 'm')
                        ->andWhere('m.gallery = :identifiers')
                        ->andWhere('m.filePath = :filePath')
                        ->setParameter('identifiers', $identifier)
                        ->setParameter('filePath', $filePath)
                        ->getQuery()->getArrayResult();

        $result = count($result) !== 0 ? $result[0] : null;
        
        return $result;
    }
}
