<?php

namespace Webkul\Magento2Bundle\Repository;

/**
 * ProductMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMappingRepository extends \Doctrine\ORM\EntityRepository
{
}
