services:
    acme_xlsx_connector.job.xlsx_custom_product_import:
            class: '%pim_connector.job.simple_job.class%'
            arguments:
                - 'xlsx_custom_product_import'
                - '@event_dispatcher'
                - '@akeneo_batch.job_repository'
                -
                    - '@acme_xlsx_connector.step.xlsx_custom_product_import.import'
            tags:
                - { name: akeneo_batch.job, connector: 'Akeneo XLSX Connector', type: '%pim_connector.job.import_type%' }