parameters:
    acme.connector.processor.custom.class: Acme\Bundle\XlsxConnectorBundle\Connector\Processor\CustomProcessor

services:
    acme.connector.processor.custom:
        class: '%acme.connector.processor.custom.class%'
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_connector.processor.denormalization.product_to_import'
            - '@pim_catalog.entity_with_family_variant.add_parent_to_product'
            - '@pim_catalog.updater.product'
            - '@pim_catalog.validator.product'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_catalog.comparator.filter.product'
            - '@pim_connector.processor.attribute_filter.product'
            - '@pim_connector.processor.denormalization.media_storer'
            - '@pim_catalog.entity_with_family_variant.remove_parent_from_product'